import React, { useEffect } from 'react';
import { ArrowLeft, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

export default function TermsOfService() {
  const navigate = useNavigate();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[#FDFDFB] text-[#1D1D1B] font-serif selection:bg-km-red/10 overflow-x-hidden">
      <div className="fixed inset-0 pointer-events-none opacity-[0.03] z-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')]"></div>
      
      <header className="fixed top-0 left-0 w-full bg-white/80 backdrop-blur-md border-b border-[#F0F0EE] z-50 px-6 py-4 flex items-center justify-between">
        <button 
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-widest text-[#CBCBC9] hover:text-km-red transition-colors"
        >
          <ArrowLeft size={14} /> Back
        </button>
        <span className="font-display text-xl uppercase tracking-widest">Keep Meaning</span>
        <div className="w-16"></div>
      </header>

      <main className="max-w-3xl mx-auto px-6 pt-32 pb-24 relative z-10">
        <div className="mb-16 space-y-4">
          <div className="w-12 h-12 bg-km-red/5 rounded-2xl flex items-center justify-center mb-6 border border-km-red/10">
            <FileText className="text-km-red w-6 h-6" />
          </div>
          <h1 className="font-display text-4xl md:text-5xl uppercase tracking-tighter leading-none">Terms of Service</h1>
          <p className="text-[10px] font-bold uppercase tracking-widest text-[#8E8E8E]">Last updated March 14, 2026</p>
        </div>

        <div className="space-y-12 text-lg leading-relaxed text-black/80">
          <section className="space-y-4">
            <p>
              These Terms of Service ("Terms") constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you") and Keep Meaning ("Company", "we", "us", or "our"), concerning your access to and use of the https://www.keepmeaning.xyz website as well as any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto (collectively, the "Site").
            </p>
            <p>
              By accessing the Site, you agree that you have read, understood, and agree to be bound by all of these Terms of Service. IF YOU DO NOT AGREE WITH ALL OF THESE TERMS OF SERVICE, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.
            </p>
          </section>

          <section className="space-y-6">
            <h2 className="font-sans text-xs font-bold uppercase tracking-[0.2em] text-km-red border-b border-[#F0F0EE] pb-4">1. Use of AI and Content Generation</h2>
            <p>Keep Meaning provides an artificial intelligence-based editorial engine. By using our services, you understand and agree that:</p>
            <ul className="list-disc pl-6 space-y-2 opacity-80">
              <li>The output generated by the service is powered by third-party AI providers (including Mistral AI).</li>
              <li>You are solely responsible for reviewing, verifying, and deciding whether to publish the generated content.</li>
              <li>We do not claim ownership over the raw drafts you input, nor the final artifacts generated using your specific 'Voice DNA'.</li>
            </ul>
          </section>

          <section className="space-y-6">
            <h2 className="font-sans text-xs font-bold uppercase tracking-[0.2em] text-km-red border-b border-[#F0F0EE] pb-4">2. User Representations</h2>
            <p>By using the Site, you represent and warrant that:</p>
            <ul className="list-disc pl-6 space-y-2 opacity-80">
              <li>All registration information you submit will be true, accurate, current, and complete.</li>
              <li>You will maintain the accuracy of such information and promptly update such registration information as necessary.</li>
              <li>You have the legal capacity and you agree to comply with these Terms of Service.</li>
              <li>You are not a minor in the jurisdiction in which you reside.</li>
            </ul>
          </section>

          <section className="space-y-6">
            <h2 className="font-sans text-xs font-bold uppercase tracking-[0.2em] text-km-red border-b border-[#F0F0EE] pb-4">3. Contact Us</h2>
            <p>In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at:</p>
            <p className="font-bold">info@keepmeaning.xyz</p>
          </section>
        </div>
      </main>
    </div>
  );
}
